// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Soundy",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Soundy",
            targets: ["AppModule"],
            bundleIdentifier: "app.yuzawa.atti.Soundy",
            teamIdentifier: "VJBS649B8H",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .moon),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Assets/LaPrimavera.wav")
            ]
        )
    ],
    swiftLanguageVersions: [.v6]
)
